(function () {
    var root = typeof global !== 'undefined' ? global : this;

    /**
     * Global object with classes, properties and methods you can access from anywhere.
     *
     * See [methods and properties](../classes/Editor.html).
     * @module Editor
     * @main Editor
     */
    /**
     * Global object with classes, properties and methods you can access from anywhere
     *
     * See [classes in Editor module](../modules/Editor.html).
     * @class Editor
     * @static
     */
    var Editor = root.Editor || {};
    root.Editor = Editor;

    var JS = Fire.JS;
    var FObject = Fire.FObject;
    var HashObject = Fire.HashObject;
    var Asset = Fire.Asset;
    var Vec2 = Fire.Vec2;
    var v2 = Fire.v2;
    var Matrix23 = Fire.Matrix23;
    var Rect = Fire.Rect;
    var Color = Fire.Color;
    var Texture = Fire.Texture;
    var Sprite = Fire.Sprite;
    var Atlas = Fire.Atlas;

    // The codes below is generated by script automatically:
    // <%=contents%>
    // end of generated codes

}).call(this);
